use crate::custom_material::RaytraceShaderCompiler;
use crate::math::*;
use crate::rendering::renderer::RenderParams;
use crate::rendering::texture::set_wgpu_device_queue;
use crate::scene::object::{
    GpuAtmosphere, GpuCustomMaterial, GpuMaterial, GpuObject, GpuTriangle, MAX_ATMOSPHERES,
};
use crate::scene::{bvh::GpuBvhNode, tri_bvh::GpuTriBvhNode};
use bytemuck::Zeroable;
use egui::{ClippedPrimitive, TexturesDelta};
use sdl2::video::Window;
use std::collections::hash_map::DefaultHasher;
use std::hash::{Hash, Hasher};
use std::num::NonZeroU64;
use std::time::Instant;
use wgpu::rwh::{HasDisplayHandle, HasWindowHandle};
use wgpu::SurfaceTargetUnsafe;
use wgpu::{util::DeviceExt, *};

use super::setup::{create_atmosphere_lut_textures, create_textures, init_wgpu};
use super::types::*;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum MainComputePipelineKind {
    Bootstrap,
    HybridCompose,
    CinematicPathTrace,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum LazyPipelineStatus {
    NotCompiled,
    Compiled,
    Failed,
}

pub struct WgpuRenderer {
    surface: Surface<'static>,
    device: std::sync::Arc<Device>,
    queue: std::sync::Arc<Queue>,
    config: SurfaceConfiguration,
    surface_width: u32,
    surface_height: u32,
    width: u32,
    height: u32,
    render_scale: f32,
    sharpness: f32,
    is_2d: bool,
    object_buffer: Buffer,
    object_buffer_capacity: usize,
    cloud_buffer: Buffer,
    params_buffer: Buffer,
    blit_params_buffer: Buffer,
    screen_texture: Texture,
    screen_view: TextureView,
    screen_history_texture: Texture,
    screen_history_view: TextureView,
    depth_texture: Texture,
    depth_view: TextureView,
    depth_stencil_texture: Texture,
    depth_stencil_view: TextureView,
    normal_texture: Texture,
    normal_view: TextureView,
    color_texture: Texture,
    color_view: TextureView,
    gbuf_albedo_texture: Texture,
    gbuf_albedo_view: TextureView,
    gbuf_normal_texture: Texture,
    gbuf_normal_view: TextureView,
    gbuf_material_texture: Texture,
    gbuf_material_view: TextureView,
    gi_sdf_texture: Texture,
    gi_sdf_view: TextureView,
    gi_sdf_storage_view: TextureView,
    gi_radiance_texture: Texture,
    gi_radiance_view: TextureView,
    gi_radiance_storage_view: TextureView,
    gi_cache: GiCacheState,
    gi_history_texture: Texture,
    gi_history_view: TextureView,
    gi_noisy_texture: Texture,
    gi_noisy_view: TextureView,
    gi_buffer_texture: Texture,
    gi_buffer_view: TextureView,
    motion_texture: Texture,
    motion_view: TextureView,
    variance_texture: Texture,
    variance_view: TextureView,
    lightmap_texture: Texture,
    lightmap_view: TextureView,
    transmittance_lut_texture: Texture,
    transmittance_lut_view: TextureView,
    transmittance_lut_storage_view: TextureView,
    sky_view_lut_texture: Texture,
    sky_view_lut_view: TextureView,
    sky_view_lut_storage_view: TextureView,
    multi_scattering_lut_texture: Texture,
    multi_scattering_lut_view: TextureView,
    multi_scattering_lut_storage_view: TextureView,
    aerial_perspective_lut_texture: Texture,
    aerial_perspective_lut_view: TextureView,
    aerial_perspective_lut_storage_view: TextureView,
    depth_history_texture: Texture,
    depth_history_view: TextureView,
    normal_history_texture: Texture,
    normal_history_view: TextureView,
    occluder_texture: Texture,
    occluder_view: TextureView,
    white_texture: crate::gpu::TextureHandle,
    blue_noise_texture: crate::gpu::TextureHandle,
    _cloud_shape_noise_texture: Texture,
    cloud_shape_noise_view: TextureView,
    _cloud_detail_noise_texture: Texture,
    cloud_detail_noise_view: TextureView,
    _cloud_weather_texture: Texture,
    cloud_weather_view: TextureView,
    cloud_radiance_texture: Texture,
    cloud_radiance_view: TextureView,
    cloud_radiance_history_texture: Texture,
    cloud_radiance_history_view: TextureView,
    cloud_transmittance_texture: Texture,
    cloud_transmittance_view: TextureView,
    cloud_transmittance_history_texture: Texture,
    cloud_transmittance_history_view: TextureView,
    cloud_shadow_texture: Texture,
    cloud_shadow_view: TextureView,
    cloud_shadow_history_texture: Texture,
    cloud_shadow_history_view: TextureView,
    raster_shadow_texture: Texture,
    raster_shadow_view: TextureView,
    raster_shadow_sampler: Sampler,
    raster_shadow_view_proj_buffer: Buffer,
    material_textures: Vec<crate::gpu::TextureHandle>,
    gi_params_buffer: Buffer,
    postfx_buffer: Buffer,
    light_buffer: Buffer,
    post_fx_uniforms: PostFxUniforms,
    sdfgi_bind_group_layout: BindGroupLayout,
    sdfgi_bind_group: BindGroup,
    sdfgi_pipeline: ComputePipeline,
    sdfgi_inject_bind_group_layout: BindGroupLayout,
    sdfgi_inject_bind_group: BindGroup,
    sdfgi_inject_pipeline: ComputePipeline,
    sdfgi_mip_bind_group_layout: BindGroupLayout,
    sdfgi_mip_bind_groups: Vec<BindGroup>,
    sdfgi_mip_pipeline: ComputePipeline,
    atmosphere_lut_bind_group_layout: BindGroupLayout,
    transmittance_lut_bind_group: BindGroup,
    transmittance_lut_pipeline: ComputePipeline,
    sky_view_lut_bind_group: BindGroup,
    sky_view_lut_pipeline: ComputePipeline,
    multi_scattering_lut_bind_group: BindGroup,
    multi_scattering_lut_pipeline: ComputePipeline,
    aerial_perspective_lut_bind_group: BindGroup,
    aerial_perspective_lut_pipeline: ComputePipeline,
    sampler: Sampler,
    linear_sampler: Sampler,
    shader_compiler: RaytraceShaderCompiler,
    compute_bind_group_layout: BindGroupLayout,
    compute_bind_group: BindGroup,
    compute_pipeline: ComputePipeline,
    cloud_shadow_pipeline: ComputePipeline,
    hybrid_rt_shadow_texture: Texture,
    hybrid_rt_shadow_view: TextureView,
    hybrid_rt_reflection_texture: Texture,
    hybrid_rt_reflection_view: TextureView,
    hybrid_rt_reflection_history_texture: Texture,
    hybrid_rt_reflection_history_view: TextureView,
    hybrid_rt_gi_texture: Texture,
    hybrid_rt_gi_view: TextureView,
    hybrid_rt_transparency_texture: Texture,
    hybrid_rt_transparency_view: TextureView,
    hybrid_rt_params_buffer: Buffer,
    hybrid_composite_params_buffer: Buffer,
    hybrid_rt_effect_bind_group_layout: BindGroupLayout,
    hybrid_rt_shadow_bind_group: BindGroup,
    hybrid_rt_reflection_bind_group: BindGroup,
    hybrid_rt_gi_bind_group: BindGroup,
    hybrid_rt_transparency_bind_group: BindGroup,
    hybrid_composite_bind_group_layout: BindGroupLayout,
    hybrid_composite_bind_group: BindGroup,
    hybrid_rt_shadow_pipeline: Option<ComputePipeline>,
    hybrid_rt_reflection_pipeline: Option<ComputePipeline>,
    hybrid_rt_gi_pipeline: Option<ComputePipeline>,
    hybrid_rt_transparency_pipeline: Option<ComputePipeline>,
    hybrid_compose_pipeline: Option<ComputePipeline>,
    hybrid_compose_pipeline_error: Option<String>,
    cinematic_compute_pipeline: Option<ComputePipeline>,
    cinematic_cloud_shadow_pipeline: Option<ComputePipeline>,
    cinematic_pipeline_status: LazyPipelineStatus,
    cinematic_pipeline_error: Option<String>,
    active_compute_pipeline_kind: MainComputePipelineKind,
    safe_shader_mode: bool,
    pending_material_names: Vec<String>,
    pending_shader_defs: Vec<(String, String)>,
    denoise_bind_group_layout: BindGroupLayout,
    denoise_bind_group: BindGroup,
    denoise_pipeline: ComputePipeline,
    rt_denoise_bind_group_layout: BindGroupLayout,
    rt_denoise_bind_group: BindGroup,
    rt_denoise_pipeline: ComputePipeline,
    render_bind_group_layout: BindGroupLayout,
    render_bind_group: BindGroup,
    render_pipeline: RenderPipeline,
    blur_bind_group_layout: BindGroupLayout,
    blur_bind_group: BindGroup,
    blur_pipeline: RenderPipeline,
    blur_params_buffer: Buffer,
    blur_src_texture: Texture,
    blur_src_view: TextureView,
    pending_blur_regions: Vec<(u32, u32, u32, u32)>,
    blur_feather: f32,
    sprite_bind_group_layout: BindGroupLayout,
    sprite_pipeline: RenderPipeline,
    occluder_pipeline: RenderPipeline,
    sprite_vertex_buffer: Buffer,
    sprite_view_proj_buffer: Buffer,
    pbr_bind_group_layout: BindGroupLayout,
    pbr_shadow_bind_group_layout: BindGroupLayout,
    pbr_pipeline: RenderPipeline,
    primitive_gbuffer_bind_group_layout: BindGroupLayout,
    primitive_gbuffer_bind_group: BindGroup,
    primitive_gbuffer_pipeline: RenderPipeline,
    primitive_shadow_pipeline: RenderPipeline,
    pbr_shadow_pipeline: RenderPipeline,
    primitive_cube_vertex_buffer: Buffer,
    primitive_cube_index_buffer: Buffer,
    primitive_cube_index_count: u32,
    primitive_sphere_vertex_buffer: Buffer,
    primitive_sphere_index_buffer: Buffer,
    primitive_sphere_index_count: u32,
    prev_raster_primitive_count: Option<u32>,
    pub prev_view_proj: [[f32; 4]; 4],
    prev_taa_jitter: [f32; 2],
    triangle_buffer: Buffer,
    bvh_buffer: Buffer,
    tri_bvh_buffer: Buffer,
    material_buffer: Buffer,
    custom_material_buffer: Buffer,
    light_header_buffer: Buffer,
    light_index_buffer: Buffer,
    triangle_count: u32,
    bvh_node_count: u32,
    tri_bvh_node_count: u32,
    material_count: u32,
    custom_material_count: u32,
    pub frame_number: i32,
    prev_cam_pos: [f32; 3],
    prev_cam_front: [f32; 3],
    prev_cam_up: [f32; 3],
    prev_cam_right: [f32; 3],
    prev_num_objects: i32,
    prev_shader_params: Option<ShaderParams>,
    prev_gi_params: Option<GiParams>,
    prev_blit_params: Option<BlitParams>,
    prev_post_fx_uniforms: Option<PostFxUniforms>,
    prev_sprite_view_proj: Option<[f32; 16]>,
    prev_light_data: Option<LightUniform>,
    sprite_vertices_cache: Vec<[f32; 5]>,
    prev_material_names: Vec<String>,
    prev_material_fallback_tags: u32,
    prev_shader_defs: Vec<(String, String)>,
    prev_objects: Vec<GpuObject>,
    prev_triangles: Vec<GpuTriangle>,
    profiler_stats: crate::rendering::renderer::RendererProfilerStats,
    adaptive_quality: f32,
    slow_frame_streak: u32,
    fast_frame_streak: u32,
    prev_bvh_nodes: Vec<GpuBvhNode>,
    prev_tri_bvh_nodes: Vec<GpuTriBvhNode>,
    profiler_query_set: Option<QuerySet>,
    profiler_query_buffer: Option<Buffer>,
    profiler_readback_buffer: Option<Buffer>,
    profiler_timestamp_period: f32,
}

#[derive(Default)]
struct GiCacheState {
    dirty: bool,
    scene_hash: u64,
    geometry_hash: u64,
    material_light_hash: u64,
    static_scene_hash: u64,
    last_baked_scene_hash: u64,
    bake_settings_hash: u64,
    artifact_path: Option<std::path::PathBuf>,
    probe_metadata: Option<String>,
}

impl GiCacheState {
    fn mark_dirty(&mut self) {
        self.dirty = true;
    }
}

include!("renderer_impl.inc.rs");
