use crate::math::*;
use crate::rendering::renderer::RenderParams;
use crate::rendering::texture::set_wgpu_device_queue;
use crate::scene::object::{
    GpuAtmosphere, GpuCustomMaterial, GpuMaterial, GpuObject, GpuTriangle, MAX_ATMOSPHERES,
};
use crate::custom_material::RaytraceShaderCompiler;
use crate::scene::{bvh::GpuBvhNode, tri_bvh::GpuTriBvhNode};
use bytemuck::Zeroable;
use egui::{ClippedPrimitive, TexturesDelta};
use sdl2::video::Window;
use wgpu::SurfaceTargetUnsafe;
use wgpu::rwh::{HasDisplayHandle, HasWindowHandle};
use wgpu::{util::DeviceExt, *};
use std::num::NonZeroU64;

use super::setup::{create_textures, init_wgpu};
use super::types::*;

pub struct WgpuRenderer {
    surface: Surface<'static>,
    device: std::sync::Arc<Device>,
    queue: std::sync::Arc<Queue>,
    config: SurfaceConfiguration,
    width: u32,
    height: u32,
    is_2d: bool,
    object_buffer: Buffer,
    params_buffer: Buffer,
    blit_params_buffer: Buffer,
    screen_texture: Texture,
    screen_view: TextureView,
    screen_history_texture: Texture,
    screen_history_view: TextureView,
    depth_texture: Texture,
    depth_view: TextureView,
    depth_stencil_texture: Texture,
    depth_stencil_view: TextureView,
    normal_texture: Texture,
    normal_view: TextureView,
    color_texture: Texture,
    color_view: TextureView,
    gbuf_albedo_texture: Texture,
    gbuf_albedo_view: TextureView,
    gbuf_normal_texture: Texture,
    gbuf_normal_view: TextureView,
    gbuf_material_texture: Texture,
    gbuf_material_view: TextureView,
    gi_sdf_texture: Texture,
    gi_sdf_view: TextureView,
    gi_sdf_storage_view: TextureView,
    gi_radiance_texture: Texture,
    gi_radiance_view: TextureView,
    gi_radiance_storage_view: TextureView,
    gi_history_texture: Texture,
    gi_history_view: TextureView,
    gi_noisy_texture: Texture,
    gi_noisy_view: TextureView,
    gi_buffer_texture: Texture,
    gi_buffer_view: TextureView,
    motion_texture: Texture,
    motion_view: TextureView,
    variance_texture: Texture,
    variance_view: TextureView,
    lightmap_texture: Texture,
    lightmap_view: TextureView,
    depth_history_texture: Texture,
    depth_history_view: TextureView,
    normal_history_texture: Texture,
    normal_history_view: TextureView,
    occluder_texture: Texture,
    occluder_view: TextureView,
    white_texture: crate::gpu::TextureHandle,
    material_textures: Vec<crate::gpu::TextureHandle>,
    gi_params_buffer: Buffer,
    postfx_buffer: Buffer,
    light_buffer: Buffer,
    post_fx_uniforms: PostFxUniforms,
    sdfgi_bind_group_layout: BindGroupLayout,
    sdfgi_bind_group: BindGroup,
    sdfgi_pipeline: ComputePipeline,
    sdfgi_inject_bind_group_layout: BindGroupLayout,
    sdfgi_inject_bind_group: BindGroup,
    sdfgi_inject_pipeline: ComputePipeline,
    sdfgi_mip_bind_group_layout: BindGroupLayout,
    sdfgi_mip_pipeline: ComputePipeline,
    sampler: Sampler,
    linear_sampler: Sampler,
    shader_compiler: RaytraceShaderCompiler,
    compute_bind_group_layout: BindGroupLayout,
    compute_bind_group: BindGroup,
    compute_pipeline: ComputePipeline,
    denoise_bind_group_layout: BindGroupLayout,
    denoise_bind_group: BindGroup,
    denoise_pipeline: ComputePipeline,
    rt_denoise_bind_group_layout: BindGroupLayout,
    rt_denoise_bind_group: BindGroup,
    rt_denoise_pipeline: ComputePipeline,
    outline_bind_group_layout: BindGroupLayout,
    outline_bind_group: BindGroup,
    outline_pipeline: ComputePipeline,
    render_bind_group_layout: BindGroupLayout,
    render_bind_group: BindGroup,
    render_pipeline: RenderPipeline,
    blur_bind_group_layout: BindGroupLayout,
    blur_bind_group: BindGroup,
    blur_pipeline: RenderPipeline,
    blur_params_buffer: Buffer,
    blur_src_texture: Texture,
    blur_src_view: TextureView,
    pending_blur_regions: Vec<(u32, u32, u32, u32)>,
    blur_feather: f32,
    sprite_bind_group_layout: BindGroupLayout,
    sprite_pipeline: RenderPipeline,
    occluder_pipeline: RenderPipeline,
    sprite_vertex_buffer: Buffer,
    sprite_view_proj_buffer: Buffer,
    pbr_bind_group_layout: BindGroupLayout,
    pbr_pipeline: RenderPipeline,
    pub prev_view_proj: [[f32; 4]; 4],
    prev_taa_jitter: [f32; 2],
    triangle_buffer: Buffer,
    bvh_buffer: Buffer,
    tri_bvh_buffer: Buffer,
    material_buffer: Buffer,
    custom_material_buffer: Buffer,
    light_header_buffer: Buffer,
    light_index_buffer: Buffer,
    triangle_count: u32,
    bvh_node_count: u32,
    tri_bvh_node_count: u32,
    material_count: u32,
    custom_material_count: u32,
    frame_number: i32,
    prev_cam_pos: [f32; 3],
    prev_cam_front: [f32; 3],
    prev_cam_up: [f32; 3],
    prev_cam_right: [f32; 3],
    prev_num_objects: i32,
    prev_shader_params: Option<ShaderParams>,
    prev_gi_params: Option<GiParams>,
    prev_blit_params: Option<BlitParams>,
    prev_post_fx_uniforms: Option<PostFxUniforms>,
    prev_sprite_view_proj: Option<[f32; 16]>,
    prev_light_data: Option<LightUniform>,
    sprite_vertices_cache: Vec<[f32; 5]>,
}

include!("renderer_impl.inc.rs");