use std::collections::{HashMap, HashSet};

use glam::Vec3;

use crate::ecs::Component;
use crate::inspector::export::{ExportKind, ExportedField};
use crate::inspector::Inspectable;

/// Simple automatic Level of Detail component
#[derive(Debug, Clone)]
pub struct AutoLod {
    /// Whether LOD is enabled for this object
    pub enabled: bool,
    /// Current distance from camera
    pub distance: f32,
    /// Current LOD level being used
    pub current_level: u8,
    /// Original vertex/triangle count (for stats)
    pub original_triangles: usize,
    /// Current active triangles (after LOD)
    pub active_triangles: usize,
    /// Whether object should be culled (too far)
    pub culled: bool,
    /// Hash of the original mesh so we don't rehash every frame
    pub mesh_hash: Option<u64>,
    /// Original mesh data for restoring full detail
    pub original_mesh: Option<SimplifiedMesh>,
}

impl Default for AutoLod {
    fn default() -> Self {
        Self {
            enabled: true,
            distance: 0.0,
            current_level: 0,
            original_triangles: 0,
            active_triangles: 0,
            culled: false,
            mesh_hash: None,
            original_mesh: None,
        }
    }
}

impl Component for AutoLod {}

impl Inspectable for AutoLod {
    fn exported_fields_mut(&mut self) -> Vec<ExportedField> {
        vec![
            ExportedField {
                name: "enabled",
                kind: ExportKind::Checkbox,
                value: &mut self.enabled as *mut _ as *mut dyn std::any::Any,
                type_id: std::any::TypeId::of::<bool>(),
            },
            ExportedField {
                name: "current_level",
                kind: ExportKind::Slider { min: 0.0, max: 8.0 },
                value: &mut self.current_level as *mut _ as *mut dyn std::any::Any,
                type_id: std::any::TypeId::of::<u8>(),
            },
            ExportedField {
                name: "culled",
                kind: ExportKind::Checkbox,
                value: &mut self.culled as *mut _ as *mut dyn std::any::Any,
                type_id: std::any::TypeId::of::<bool>(),
            },
        ]
    }
}

/// Global LOD settings shared by the processor
#[derive(Debug, Clone)]
pub struct LodSettings {
    /// LOD levels and their distance thresholds
    pub levels: Vec<LodLevel>,
    /// Objects further than this get culled completely
    pub max_distance: f32,
    /// Prevents LOD flickering when moving back/forth
    pub hysteresis_factor: f32,
}

#[derive(Debug, Clone)]
pub struct LodLevel {
    /// Distance threshold for this level
    pub distance: f32,
    /// How much detail to keep (1.0 = full, 0.5 = half triangles, etc)
    pub detail_factor: f32,
}

impl Default for LodSettings {
    fn default() -> Self {
        Self {
            levels: vec![
                LodLevel {
                    distance: 50.0,
                    detail_factor: 1.0,
                },
                LodLevel {
                    distance: 150.0,
                    detail_factor: 0.6,
                },
                LodLevel {
                    distance: 400.0,
                    detail_factor: 0.3,
                },
                LodLevel {
                    distance: 800.0,
                    detail_factor: 0.1,
                },
            ],
            max_distance: 1500.0,
            hysteresis_factor: 1.2,
        }
    }
}

/// Simplified mesh data generated by the LOD processor
#[derive(Debug, Clone)]
pub struct SimplifiedMesh {
    pub vertices: Vec<[f32; 3]>,
    pub indices: Vec<u32>,
    pub normals: Vec<[f32; 3]>,
    pub triangle_count: usize,
}

impl MeshData for SimplifiedMesh {
    fn get_vertices(&self) -> Vec<[f32; 3]> {
        self.vertices.clone()
    }

    fn get_indices(&self) -> Vec<u32> {
        self.indices.clone()
    }

    fn get_normals(&self) -> Vec<[f32; 3]> {
        self.normals.clone()
    }

    fn triangle_count(&self) -> usize {
        self.triangle_count
    }

    fn apply_simplified(&mut self, simplified: &SimplifiedMesh) {
        *self = simplified.clone();
    }
}

/// Stats reported by the processor each frame
#[derive(Debug, Default)]
pub struct LodStats {
    pub total_objects: usize,
    pub objects_with_lod: usize,
    pub objects_culled: usize,
    pub triangles_original: usize,
    pub triangles_rendered: usize,
    pub triangles_saved: usize,
    pub cache_hits: usize,
    pub cache_misses: usize,
}

/// Trait that mesh data must implement to work with the LOD processor
pub trait MeshData {
    fn get_vertices(&self) -> Vec<[f32; 3]>;
    fn get_indices(&self) -> Vec<u32>;
    fn get_normals(&self) -> Vec<[f32; 3]>;
    fn triangle_count(&self) -> usize;
    fn apply_simplified(&mut self, simplified: &SimplifiedMesh);
}

/// Automatic LOD processor - handles mesh simplification and caching
pub struct AutoLodProcessor {
    settings: LodSettings,
    /// Cached simplified meshes [original_hash][lod_level] = simplified_mesh
    mesh_cache: HashMap<u64, Vec<SimplifiedMesh>>,
    stats: LodStats,
}

impl AutoLodProcessor {
    pub fn new() -> Self {
        Self {
            settings: LodSettings::default(),
            mesh_cache: HashMap::new(),
            stats: LodStats::default(),
        }
    }

    pub fn with_settings(settings: LodSettings) -> Self {
        Self {
            settings,
            mesh_cache: HashMap::new(),
            stats: LodStats::default(),
        }
    }

    /// Main function - call this every frame with all your objects
    pub fn update_all_objects<M: MeshData>(
        &mut self,
        objects: &mut [(&mut AutoLod, &mut M)],
        camera_position: Vec3,
    ) {
        self.stats = LodStats::default();
        self.stats.total_objects = objects.len();

        for (lod_component, mesh_data) in objects.iter_mut() {
            if lod_component.enabled {
                self.update_single_object(lod_component, *mesh_data, camera_position);
                self.stats.objects_with_lod += 1;
            } else {
                lod_component.active_triangles = mesh_data.triangle_count();
            }
        }

        self.stats.triangles_saved = self
            .stats
            .triangles_original
            .saturating_sub(self.stats.triangles_rendered);
    }

    /// Update a single object's LOD
    fn update_single_object<M: MeshData>(
        &mut self,
        lod: &mut AutoLod,
        mesh: &mut M,
        camera_pos: Vec3,
    ) {
        if lod.mesh_hash.is_none() {
            lod.mesh_hash = Some(self.hash_mesh(mesh));
            if lod.original_triangles == 0 {
                lod.original_triangles = mesh.triangle_count();
            }
            if lod.original_mesh.is_none() {
                lod.original_mesh = Some(SimplifiedMesh {
                    vertices: mesh.get_vertices(),
                    indices: mesh.get_indices(),
                    normals: mesh.get_normals(),
                    triangle_count: lod.original_triangles,
                });
            }
        }

        let object_pos = if let Some(orig) = &lod.original_mesh {
            self.calculate_mesh_center(orig)
        } else {
            self.calculate_mesh_center(mesh)
        };
        let distance = camera_pos.distance(object_pos);
        lod.distance = distance;

        if distance > self.settings.max_distance {
            lod.culled = true;
            lod.active_triangles = 0;
            self.stats.objects_culled += 1;
            return;
        }

        lod.culled = false;

        let new_level = self.calculate_lod_level(distance, lod.current_level);

        if new_level != lod.current_level {
            lod.current_level = new_level;
            self.apply_lod_to_mesh(mesh, new_level, lod);
        }

        self.stats.triangles_original += lod.original_triangles;
        self.stats.triangles_rendered += lod.active_triangles;
    }

    /// Determine which LOD level to use
    fn calculate_lod_level(&self, distance: f32, current_level: u8) -> u8 {
        let mut target_level = 0u8;

        for (i, level_config) in self.settings.levels.iter().enumerate() {
            if distance > level_config.distance {
                target_level = (i + 1) as u8;
            } else {
                break;
            }
        }

        if target_level != current_level {
            let threshold_distance = if target_level > 0 {
                self.settings
                    .levels
                    .get(target_level as usize - 1)
                    .map(|l| l.distance)
                    .unwrap_or(0.0)
            } else {
                0.0
            };

            let hysteresis_distance = if target_level > current_level {
                threshold_distance
            } else {
                threshold_distance * self.settings.hysteresis_factor
            };

            if target_level > current_level && distance <= hysteresis_distance {
                target_level = current_level;
            }
        }

        target_level.min((self.settings.levels.len() - 1) as u8)
    }

    /// Apply LOD to mesh - generates or retrieves a simplified mesh
    fn apply_lod_to_mesh<M: MeshData>(&mut self, mesh: &mut M, level: u8, lod: &mut AutoLod) {
        if level == 0 {
            if let Some(original) = &lod.original_mesh {
                mesh.apply_simplified(original);
                lod.active_triangles = original.triangle_count;
            } else {
                lod.active_triangles = mesh.triangle_count();
            }
            return;
        }

        let detail_factor = self
            .settings
            .levels
            .get(level as usize)
            .map(|l| l.detail_factor)
            .unwrap_or(0.1);

        let mesh_hash = lod.mesh_hash.unwrap_or_else(|| {
            let h = self.hash_mesh(mesh);
            lod.mesh_hash = Some(h);
            h
        });

        let original_mesh = lod
            .original_mesh
            .as_ref()
            .expect("original mesh must be captured before LOD applied");

        let simplified =
            self.get_or_create_simplified_mesh(mesh_hash, original_mesh, level, detail_factor);

        mesh.apply_simplified(&simplified);
        lod.active_triangles = simplified.triangle_count;
    }

    /// Get simplified mesh from cache or create a new one
    fn get_or_create_simplified_mesh<M: MeshData>(
        &mut self,
        mesh_hash: u64,
        original_mesh: &M,
        level: u8,
        detail_factor: f32,
    ) -> SimplifiedMesh {
        if let Some(cached_levels) = self.mesh_cache.get(&mesh_hash) {
            if let Some(cached_mesh) = cached_levels.get(level as usize) {
                self.stats.cache_hits += 1;
                return cached_mesh.clone();
            }
        }

        self.stats.cache_misses += 1;
        let simplified = self.simplify_mesh(original_mesh, detail_factor);

        let cache_entry = self.mesh_cache.entry(mesh_hash).or_insert_with(Vec::new);
        while cache_entry.len() <= level as usize {
            cache_entry.push(SimplifiedMesh {
                vertices: Vec::new(),
                indices: Vec::new(),
                normals: Vec::new(),
                triangle_count: 0,
            });
        }
        cache_entry[level as usize] = simplified.clone();

        simplified
    }

    /// Simplify mesh by uniformly sampling triangles
    fn simplify_mesh<M: MeshData>(&self, original: &M, detail_factor: f32) -> SimplifiedMesh {
        if detail_factor >= 1.0 {
            return SimplifiedMesh {
                vertices: original.get_vertices(),
                indices: original.get_indices(),
                normals: original.get_normals(),
                triangle_count: original.triangle_count(),
            };
        }

        let original_triangles = original.triangle_count();
        let target_triangles = ((original_triangles as f32 * detail_factor) as usize).max(1);

        if target_triangles >= original_triangles {
            return SimplifiedMesh {
                vertices: original.get_vertices(),
                indices: original.get_indices(),
                normals: original.get_normals(),
                triangle_count: original_triangles,
            };
        }

        let step = (original_triangles / target_triangles).max(1);
        let original_indices = original.get_indices();
        let mut new_indices = Vec::new();
        let mut used_vertices = HashSet::new();

        for i in (0..original_indices.len()).step_by(step * 3) {
            if i + 2 < original_indices.len() {
                let idx1 = original_indices[i];
                let idx2 = original_indices[i + 1];
                let idx3 = original_indices[i + 2];
                new_indices.extend_from_slice(&[idx1, idx2, idx3]);
                used_vertices.extend([idx1 as usize, idx2 as usize, idx3 as usize]);
            }
        }

        let original_vertices = original.get_vertices();
        let original_normals = original.get_normals();

        let mut vertex_map = HashMap::new();
        let mut new_vertices = Vec::new();
        let mut new_normals = Vec::new();

        for &old_idx in &used_vertices {
            if old_idx < original_vertices.len() {
                vertex_map.insert(old_idx, new_vertices.len());
                new_vertices.push(original_vertices[old_idx]);
                if old_idx < original_normals.len() {
                    new_normals.push(original_normals[old_idx]);
                }
            }
        }

        for idx in new_indices.iter_mut() {
            if let Some(&new_idx) = vertex_map.get(&(*idx as usize)) {
                *idx = new_idx as u32;
            }
        }

        let triangle_count = new_indices.len() / 3;
        SimplifiedMesh {
            vertices: new_vertices,
            indices: new_indices,
            normals: new_normals,
            triangle_count,
        }
    }

    fn calculate_mesh_center<M: MeshData>(&self, mesh: &M) -> Vec3 {
        let vertices = mesh.get_vertices();
        if vertices.is_empty() {
            return Vec3::ZERO;
        }
        let sum = vertices.iter().fold([0.0f32; 3], |acc, v| {
            [acc[0] + v[0], acc[1] + v[1], acc[2] + v[2]]
        });
        Vec3::new(
            sum[0] / vertices.len() as f32,
            sum[1] / vertices.len() as f32,
            sum[2] / vertices.len() as f32,
        )
    }

    fn hash_mesh<M: MeshData>(&self, mesh: &M) -> u64 {
        use std::collections::hash_map::DefaultHasher;
        use std::hash::{Hash, Hasher};

        let mut hasher = DefaultHasher::new();
        let vertices = mesh.get_vertices();
        let indices = mesh.get_indices();

        vertices.len().hash(&mut hasher);
        indices.len().hash(&mut hasher);

        for (i, vertex) in vertices.iter().enumerate() {
            if i % 20 == 0 {
                vertex[0].to_bits().hash(&mut hasher);
                vertex[1].to_bits().hash(&mut hasher);
                vertex[2].to_bits().hash(&mut hasher);
            }
        }

        hasher.finish()
    }

    pub fn get_stats(&self) -> &LodStats {
        &self.stats
    }

    pub fn clear_cache(&mut self) {
        self.mesh_cache.clear();
    }

    pub fn update_settings(&mut self, settings: LodSettings) {
        self.settings = settings;
        self.mesh_cache.clear();
    }
}
