use glam::Vec3;
use std::collections::{HashMap, HashSet};

use crate::ecs::Component;
use crate::inspector::export::{ExportKind, ExportedField};
use crate::inspector::Inspectable;

/// Simple automatic Level of Detail component
#[derive(Debug, Clone)]
pub struct AutoLod {
    /// Whether LOD is enabled for this object
    pub enabled: bool,
    /// Current distance from camera
    pub distance: f32,
    /// Current LOD level being used
    pub current_level: u8,
    /// Original vertex/triangle count (for stats)
    pub original_triangles: usize,
    /// Current active triangles (after LOD)
    pub active_triangles: usize,
    /// Whether object should be culled (too far)
    pub culled: bool,
}

impl Default for AutoLod {
    fn default() -> Self {
        Self {
            enabled: true,
            distance: 0.0,
            current_level: 0,
            original_triangles: 0,
            active_triangles: 0,
            culled: false,
        }
    }
}

impl Component for AutoLod {}

impl Inspectable for AutoLod {
    fn exported_fields_mut(&mut self) -> Vec<ExportedField> {
        vec![
            ExportedField {
                name: "enabled",
                kind: ExportKind::Checkbox,
                value: &mut self.enabled as *mut _ as *mut dyn std::any::Any,
                type_id: std::any::TypeId::of::<bool>(),
            },
            ExportedField {
                name: "current_level",
                kind: ExportKind::Slider { min: 0.0, max: 8.0 },
                value: &mut self.current_level as *mut _ as *mut dyn std::any::Any,
                type_id: std::any::TypeId::of::<u8>(),
            },
            ExportedField {
                name: "culled",
                kind: ExportKind::Checkbox,
                value: &mut self.culled as *mut _ as *mut dyn std::any::Any,
                type_id: std::any::TypeId::of::<bool>(),
            },
        ]
    }
}

/// Global LOD settings shared by the processor
#[derive(Debug, Clone)]
pub struct LodSettings {
    /// LOD levels and their distance thresholds
    pub levels: Vec<LodLevel>,
    /// Objects further than this get culled completely
    pub max_distance: f32,
    /// Prevents LOD flickering when moving back/forth (≥1.0)
    pub hysteresis_factor: f32,
}

#[derive(Debug, Clone)]
pub struct LodLevel {
    /// Distance threshold for this level
    pub distance: f32,
    /// How much detail to keep (1.0 = full, 0.5 = half triangles, etc)
    pub detail_factor: f32,
}

impl Default for LodSettings {
    fn default() -> Self {
        Self {
            levels: vec![
                LodLevel { distance: 50.0,  detail_factor: 1.0 },
                LodLevel { distance: 150.0, detail_factor: 0.6 },
                LodLevel { distance: 400.0, detail_factor: 0.3 },
                LodLevel { distance: 800.0, detail_factor: 0.1 },
            ],
            max_distance: 1500.0,
            hysteresis_factor: 1.2,
        }
    }
}

/// Simplified mesh data generated by the LOD processor
#[derive(Debug, Clone)]
pub struct SimplifiedMesh {
    pub vertices: Vec<[f32; 3]>,
    pub indices: Vec<u32>,
    pub normals: Vec<[f32; 3]>,
    pub triangle_count: usize,
}

/// Stats reported by the processor each frame
#[derive(Debug, Default)]
pub struct LodStats {
    pub total_objects: usize,
    pub objects_with_lod: usize,
    pub objects_culled: usize,
    pub triangles_original: usize,
    pub triangles_rendered: usize,
    pub triangles_saved: usize,
    pub cache_hits: usize,
    pub cache_misses: usize,
}

/// Trait that mesh data must implement to work with the LOD processor
pub trait MeshData {
    fn get_vertices(&self) -> Vec<[f32; 3]>;
    fn get_indices(&self) -> Vec<u32>;
    fn get_normals(&self) -> Vec<[f32; 3]>;
    fn triangle_count(&self) -> usize;
    fn apply_simplified(&mut self, simplified: &SimplifiedMesh);
}

/// Automatic LOD processor - handles mesh simplification and caching
pub struct AutoLodProcessor {
    settings: LodSettings,
    /// Cached simplified meshes [original_hash][lod_level] = simplified_mesh
    mesh_cache: HashMap<u64, Vec<SimplifiedMesh>>,
    stats: LodStats,
}

impl AutoLodProcessor {
    pub fn new() -> Self {
        Self {
            settings: LodSettings::default(),
            mesh_cache: HashMap::new(),
            stats: LodStats::default(),
        }
    }

    pub fn with_settings(settings: LodSettings) -> Self {
        Self {
            settings,
            mesh_cache: HashMap::new(),
            stats: LodStats::default(),
        }
    }

    /// Main function - call this every frame with all your objects
    pub fn update_all_objects<M: MeshData>(
        &mut self,
        objects: &mut [(&mut AutoLod, &mut M)],
        camera_position: Vec3,
    ) {
        assert!(
            !self.settings.levels.is_empty(),
            "LodSettings.levels must have at least 1 entry"
        );

        self.stats = LodStats::default();
        self.stats.total_objects = objects.len();

        for (lod_ptr, mesh_ptr) in objects.iter_mut() {
            // Fix: double-deref the pair from iter_mut()
            let lod = &mut **lod_ptr;
            let mesh = &mut **mesh_ptr;

            if lod.enabled {
                self.update_single_object(lod, mesh, camera_position);
                self.stats.objects_with_lod += 1;
            } else {
                // Count stats for disabled objects too
                if lod.original_triangles == 0 {
                    lod.original_triangles = mesh.triangle_count();
                }
                lod.culled = false;
                lod.active_triangles = lod.original_triangles;

                self.stats.triangles_original += lod.original_triangles;
                self.stats.triangles_rendered += lod.active_triangles;
            }
        }

        self.stats.triangles_saved = self
            .stats
            .triangles_original
            .saturating_sub(self.stats.triangles_rendered);
    }

    /// Update a single object's LOD
    fn update_single_object<M: MeshData>(
        &mut self,
        lod: &mut AutoLod,
        mesh: &mut M,
        camera_pos: Vec3,
    ) {
        let object_pos = self.calculate_mesh_center(mesh);
        let distance = camera_pos.distance(object_pos);
        lod.distance = distance;

        if distance > self.settings.max_distance {
            lod.culled = true;
            lod.active_triangles = 0;
            if lod.original_triangles == 0 {
                lod.original_triangles = mesh.triangle_count();
            }
            self.stats.triangles_original += lod.original_triangles;
            self.stats.objects_culled += 1;
            return;
        }

        lod.culled = false;

        let new_level = self.calculate_lod_level(distance, lod.current_level);

        if new_level != lod.current_level {
            lod.current_level = new_level;
            self.apply_lod_to_mesh(mesh, new_level, lod);
        } else if lod.active_triangles == 0 {
            // First-time fill at level 0 without a change
            lod.active_triangles = mesh.triangle_count();
        }

        if lod.original_triangles == 0 {
            lod.original_triangles = mesh.triangle_count();
        }
        self.stats.triangles_original += lod.original_triangles;
        self.stats.triangles_rendered += lod.active_triangles;
    }

    /// Determine which LOD level to use (symmetric hysteresis)
    fn calculate_lod_level(&self, distance: f32, current_level: u8) -> u8 {
        // Base target level without hysteresis
        let mut base = 0u8;
        for (i, lvl) in self.settings.levels.iter().enumerate() {
            if distance > lvl.distance {
                base = (i + 1) as u8;
            } else {
                break;
            }
        }

        let max_level = (self.settings.levels.len() - 1) as u8;
        base = base.min(max_level);

        if base == current_level {
            return current_level;
        }

        let h = self.settings.hysteresis_factor.max(1.0);

        // Moving to a coarser LOD (further away): require extra margin
        if base > current_level {
            // Threshold to leave current_level
            let leave_threshold = self.settings.levels[current_level as usize].distance * h;
            if distance < leave_threshold {
                return current_level;
            }
        } else {
            // Moving to a finer LOD (coming closer): require extra margin
            let prev_idx = current_level.saturating_sub(1) as usize;
            let enter_threshold = if current_level == 0 {
                0.0
            } else {
                self.settings.levels[prev_idx].distance / h
            };
            if distance > enter_threshold {
                return current_level;
            }
        }

        base
    }

    /// Apply LOD to mesh - generates or retrieves a simplified mesh
    fn apply_lod_to_mesh<M: MeshData>(&mut self, mesh: &mut M, level: u8, lod: &mut AutoLod) {
        if level == 0 {
            let tri = mesh.triangle_count();
            lod.active_triangles = tri;
            return;
        }

        let detail_factor = self
            .settings
            .levels
            .get(level as usize)
            .map(|l| l.detail_factor)
            .unwrap_or(0.1);

        let mesh_hash = self.hash_mesh(mesh);
        let simplified = self.get_or_create_simplified_mesh(mesh_hash, mesh, level, detail_factor);

        mesh.apply_simplified(&simplified);
        lod.active_triangles = simplified.triangle_count;
    }

    /// Get simplified mesh from cache or create a new one
    fn get_or_create_simplified_mesh<M: MeshData>(
        &mut self,
        mesh_hash: u64,
        original_mesh: &M,
        level: u8,
        detail_factor: f32,
    ) -> SimplifiedMesh {
        if let Some(cached_levels) = self.mesh_cache.get(&mesh_hash) {
            if let Some(cached_mesh) = cached_levels.get(level as usize) {
                self.stats.cache_hits += 1;
                return cached_mesh.clone();
            }
        }

        self.stats.cache_misses += 1;
        let simplified = self.simplify_mesh(original_mesh, detail_factor);

        let cache_entry = self.mesh_cache.entry(mesh_hash).or_insert_with(Vec::new);
        while cache_entry.len() <= level as usize {
            cache_entry.push(SimplifiedMesh {
                vertices: Vec::new(),
                indices: Vec::new(),
                normals: Vec::new(),
                triangle_count: 0,
            });
        }
        cache_entry[level as usize] = simplified.clone();

        simplified
    }

    /// Simplify mesh by uniformly sampling triangles (deterministic order)
    fn simplify_mesh<M: MeshData>(&self, original: &M, detail_factor: f32) -> SimplifiedMesh {
        if detail_factor >= 1.0 {
            return SimplifiedMesh {
                vertices: original.get_vertices(),
                indices: original.get_indices(),
                normals: original.get_normals(),
                triangle_count: original.triangle_count(),
            };
        }

        let original_triangles = original.triangle_count();
        let target_triangles = ((original_triangles as f32 * detail_factor) as usize).max(1);

        if target_triangles >= original_triangles {
            return SimplifiedMesh {
                vertices: original.get_vertices(),
                indices: original.get_indices(),
                normals: original.get_normals(),
                triangle_count: original_triangles,
            };
        }

        let step = (original_triangles / target_triangles).max(1);
        let original_indices = original.get_indices();
        let mut new_indices = Vec::with_capacity(target_triangles * 3);

        // Deterministic vertex collection: preserve first-seen order
        let mut used_vertices_vec: Vec<usize> = Vec::new();
        let mut used_vertices_set: HashSet<usize> = HashSet::new();

        // pick every 'step'-th triangle
        for tri_start in (0..original_indices.len()).step_by(step * 3) {
            if tri_start + 2 < original_indices.len() {
                let idx1 = original_indices[tri_start] as usize;
                let idx2 = original_indices[tri_start + 1] as usize;
                let idx3 = original_indices[tri_start + 2] as usize;

                new_indices.extend_from_slice(&[idx1 as u32, idx2 as u32, idx3 as u32]);

                if used_vertices_set.insert(idx1) { used_vertices_vec.push(idx1); }
                if used_vertices_set.insert(idx2) { used_vertices_vec.push(idx2); }
                if used_vertices_set.insert(idx3) { used_vertices_vec.push(idx3); }
            }
            if new_indices.len() / 3 >= target_triangles {
                break;
            }
        }

        let original_vertices = original.get_vertices();
        let original_normals = original.get_normals();

        let mut vertex_map = HashMap::with_capacity(used_vertices_vec.len());
        let mut new_vertices = Vec::with_capacity(used_vertices_vec.len());
        let mut new_normals = Vec::with_capacity(used_vertices_vec.len());

        for &old_idx in &used_vertices_vec {
            if old_idx < original_vertices.len() {
                vertex_map.insert(old_idx, new_vertices.len());
                new_vertices.push(original_vertices[old_idx]);

                if old_idx < original_normals.len() {
                    new_normals.push(original_normals[old_idx]);
                } else {
                    new_normals.push([0.0, 0.0, 1.0]); // safe fallback
                }
            }
        }

        // Remap indices to new contiguous vertex buffer
        for idx in new_indices.iter_mut() {
            if let Some(&new_idx) = vertex_map.get(&(*idx as usize)) {
                *idx = new_idx as u32;
            }
        }

        // Ensure normals length matches vertices
        if new_normals.len() < new_vertices.len() {
            new_normals
                .resize(new_vertices.len(), [0.0, 0.0, 1.0]);
        }

        SimplifiedMesh {
            vertices: new_vertices,
            indices: new_indices.clone(),
            normals: new_normals,
            triangle_count: new_indices.len() / 3,
        }
    }

    fn calculate_mesh_center<M: MeshData>(&self, mesh: &M) -> Vec3 {
        let vertices = mesh.get_vertices();
        if vertices.is_empty() {
            return Vec3::ZERO;
        }
        let sum = vertices.iter().fold([0.0f32; 3], |acc, v| {
            [acc[0] + v[0], acc[1] + v[1], acc[2] + v[2]]
        });
        Vec3::new(
            sum[0] / vertices.len() as f32,
            sum[1] / vertices.len() as f32,
            sum[2] / vertices.len() as f32,
        )
    }

    fn hash_mesh<M: MeshData>(&self, mesh: &M) -> u64 {
        use std::collections::hash_map::DefaultHasher;
        use std::hash::{Hash, Hasher};

        let mut hasher = DefaultHasher::new();
        let vertices = mesh.get_vertices();
        let indices = mesh.get_indices();

        vertices.len().hash(&mut hasher);
        indices.len().hash(&mut hasher);

        // sample some vertex positions
        for (i, vertex) in vertices.iter().enumerate() {
            if i % 20 == 0 {
                vertex[0].to_bits().hash(&mut hasher);
                vertex[1].to_bits().hash(&mut hasher);
                vertex[2].to_bits().hash(&mut hasher);
            }
        }
        // include a few index samples as well
        for (i, idx) in indices.iter().enumerate() {
            if i % 64 == 0 {
                idx.hash(&mut hasher);
            }
        }

        hasher.finish()
    }

    pub fn get_stats(&self) -> &LodStats {
        &self.stats
    }

    pub fn clear_cache(&mut self) {
        self.mesh_cache.clear();
    }

    pub fn update_settings(&mut self, settings: LodSettings) {
        self.settings = settings;
        self.mesh_cache.clear();
    }
}
