use super::*;

pub(crate) fn sync_main_menu_post_process(engine: &mut Engine, menu_active: bool, enabled: bool) {
    if let Some(stack) = engine.get_resource_mut::<CustomPostProcessStack>() {
        if let Some(pass) = stack.passes.iter_mut().find(|pass| pass.pass_id == "simple_shooter/vignette") { pass.enabled = enabled; pass.params = if menu_active { vec![0.72, 0.22, 0.84, 0.0] } else { vec![0.48, 0.30, 0.94, 0.0] }; }
    }
}
pub(crate) fn despawn_main_menu_page(engine: &mut Engine) { for actor in engine.actors_with::<MainMenuWidget>().into_iter().filter_map(|(actor, widget)| widget.page_only.then_some(actor)).collect::<Vec<_>>() { actor.despawn(engine); } }
pub(crate) fn spawn_menu_panel(engine: &mut Engine, anchor: Vec2, offset: Vec2, size: Vec2, page_only: bool) -> Actor { engine.spawn_actor("Main Menu Panel").with(if page_only { MainMenuWidget::page_decoration() } else { MainMenuWidget::decoration() }).with(vetrace_ui::UIScreenSpace).with(ScreenSpaceRect { anchor, offset_px: offset, size_px: size, z_order: 300 }).with(vetrace_ui::UIPanel { size, background: Vec3::new(0.025, 0.035, 0.052), alpha: 0.94, anchor: Anchor::Center }).with(vetrace_ui::UIVisualStyle::rounded(18.0).with_border(1.0, Vec3::new(0.16, 0.36, 0.58), 0.65).with_shadow(Vec2::new(0.0, 10.0), Vec3::ZERO, 0.55)).build() }
pub(crate) fn spawn_menu_label(engine: &mut Engine, text: &str, anchor: Vec2, offset: Vec2, size: Vec2, font_size: f32, color: Vec3, page_only: bool) -> Actor { engine.spawn_actor("Main Menu Label").with(if page_only { MainMenuWidget::page_decoration() } else { MainMenuWidget::decoration() }).with(vetrace_ui::UIScreenSpace).with(ScreenSpaceRect { anchor, offset_px: offset, size_px: size, z_order: 302 }).with(UILabel { text: text.to_string(), font_size, color, anchor: Anchor::Center, align: TextAlign::Center }).build() }
pub(crate) fn spawn_menu_button(engine: &mut Engine, text: &str, action: MainMenuAction, anchor: Vec2, offset: Vec2, size: Vec2, style: vetrace_ui::UIVisualStyle, background: Vec3, page_only: bool) -> Actor { engine.spawn_actor(format!("Main Menu Button: {text}")).with(if page_only { MainMenuWidget::page_button(action) } else { MainMenuWidget::button(action) }).with(vetrace_ui::UIScreenSpace).with(ScreenSpaceRect { anchor, offset_px: offset, size_px: size, z_order: 304 }).with(vetrace_ui::UIButton { text: text.to_string(), size, ..vetrace_ui::UIButton::default() }).with(style).with(Material { base_color: background, alpha: 0.97, ..Material::default() }).build() }
pub(crate) fn spawn_menu_hit_target(engine: &mut Engine, action: MainMenuAction, anchor: Vec2, offset: Vec2, size: Vec2) -> Actor { engine.spawn_actor("Main Menu Player Hit Target").with(MainMenuWidget::button(action)).with(vetrace_ui::UIScreenSpace).with(ScreenSpaceRect { anchor, offset_px: offset, size_px: size, z_order: 250 }).build() }
pub(crate) fn menu_dark_button_style() -> vetrace_ui::UIVisualStyle { vetrace_ui::UIVisualStyle::rounded(12.0).with_border(1.0, Vec3::new(0.20, 0.40, 0.62), 0.65).with_shadow(Vec2::new(0.0, 5.0), Vec3::ZERO, 0.42) }
pub(crate) fn menu_accent_button_style() -> vetrace_ui::UIVisualStyle { let mut style = menu_dark_button_style(); style.font_size = 16.0; style.hover_brightness = 0.18; style }
pub(crate) fn menu_play_button_style() -> vetrace_ui::UIVisualStyle { let mut style = vetrace_ui::UIVisualStyle::rounded(16.0).with_border(2.0, Vec3::new(1.0, 0.88, 0.30), 0.95).with_shadow(Vec2::new(0.0, 8.0), Vec3::new(0.18, 0.10, 0.0), 0.65); style.text_color = Vec3::new(0.10, 0.075, 0.01); style.font_size = 22.0; style.hover_brightness = 0.22; style }
